### ISSUE TITLE
Creating payments invoice is failing 

### ISSUE THREAD

**Issue by escalopa** [SakoDroid/telego#15] opened 2023-03-28 10:47 UTC
Hey!

I have been struggling with creating a payment invoice using the `telego` package, I wonder whether if I am doing something wrong.

Here is my code

```go
providerToken := "123:XXXX:123" 
err = bot.AddHandler("/pay", func(u *objs.Update) {
	kb := bot.CreateInlineKeyboard()
	kb.AddCallbackButtonHandler("Buy", "pay", 1, func(u *objs.Update) {
		_, err = bot.SendMessage(u.CallbackQuery.Message.Chat.Id, "Payed", "", 0, false, false)
		if err != nil {
			log.Println(err)
		}
	})
	inv := bot.AdvancedMode().ACreateInvoice(
		u.Message.Chat.Id,
		"Test invoice",
		"description here",
		"custom_payload",
		providerToken,
		"USD",
		[]objs.LabeledPrice{{Label: "USD", Amount: 200}},
		40,
		[]int{10, 20},
		"start_param",
		"",
		"",
		0,
		0,
		0,
		true,
		true,
		true,
		false,
		false,
		false,
		false,
		false,
		false,
		kb,
	)
	_, err = inv.Send(u.Message.MessageId, false)
	if err != nil {
		log.Println(err)
	}
}, "private")
```

I get the following error when creating it 

```log
2023/03/28 13:21:19 Unable to send sendInvoice. received status code 400
Error code : 400, Description : Bad Request: REPLY_MARKUP_BUY_EMPTY
```

I tried doing something similar with the default [telegram package for go](https://github.com/go-telegram-bot-api/telegram-bot-api) and things worked just fine.

**Comment by SakoDroid** [comment] 2023-06-10 08:47
Hi @escalopa, thanks for your report, This is a bug caused by a malfunction in the code and will be fixed in the next release.
Feel free to report any further bugs, thanks!

**Comment by SakoDroid** [comment] 2023-06-10 09:04
Hi @escalopa , sorry for replying late and thanks for reaching out. According to the [invoice section](https://core.telegram.org/bots/api#sendinvoice) of the telegram bot API docs, the first key of the keyboard sent with the invoice should be a pay button. But looking at the code snippet you posted here, you haven't added any pay button to the keyboard.
Use `AddPayButton` method of InlineKeyboard objetct to add a pay button to your keyboard.

Feel free to ask any further questions and report a bug if you see one, thanks alot!
Good Luck

**Closed** 2023-06-15 13:11 UTC
Labels: good first issue
