### ISSUE TITLE
local error: tls: bad record MAC

### ISSUE THREAD

**Issue by stshishkin** [SakoDroid/telego#5] opened 2022-07-03 22:58 UTC
It looks like there are some problems with the webhook set-up.

I've got the following errors with letsencrypt certificate:
`2022/07/03 21:36:16 http: TLS handshake error from 91.108.6.111:38992: local error: tls: bad record MAC`
with such configuration:
```golang
func main() {
	whcfg := &cfg.WebHookConfigs{
		URL:      "https://domain.com:8443",
		KeyFile:  "privkey.pem",
		CertFile: "fullchain.pem",
		Port:     8443,
	}
	cf := cfg.BotConfigs{BotAPI: cfg.DefaultBotAPI, APIKey: "123456789:AbCdEfGhIjKlMnOpQrStUvWxYz012345678", Webhook: true, WebHookConfigs: whcfg, LogFileAddress: cfg.DefaultLogFile}

	var err error

	bot, err = bt.NewBot(&cf)
	if err == nil {
		err = bot.Run()
		if err == nil {
			start()
		} else {
			fmt.Println(err)
		}
	} else {
		fmt.Println(err)
	}
}
```

and answer on `https://api.telegram.org/bot123456789:AbCdEfGhIjKlMnOpQrStUvWxYz012345678/getWebhookInfo`:
```json
  {
	"ok": true,
	"result": {
	  "url": "https://domain.com:8443/123456789:AbCdEfGhIjKlMnOpQrStUvWxYz012345678",
	  "has_custom_certificate": true,
	  "pending_update_count": 1,
	  "last_error_date": 1656910960,
	  "last_error_message": "SSL error {error:0A000086:SSL routines::certificate verify failed}",
	  "max_connections": 40,
	  "ip_address": "1.2.3.4"
	}
  }
```

for example the following configuration on [github.com/go-telegram-bot-api/telegram-bot-api](https://github.com/go-telegram-bot-api/telegram-bot-api)

```golang
func main() {
	bot, err := tgbotapi.NewBotAPI("123456789:AbCdEfGhIjKlMnOpQrStUvWxYz012345678")
	if err != nil {
		log.Fatal(err)
	}

	bot.Debug = true

	log.Printf("Authorized on account %s", bot.Self.UserName)

	wh, _ := tgbotapi.NewWebhook("https://domain.com:8443/"+bot.Token)

	_, err = bot.Request(wh)
	if err != nil {
		log.Fatal(err)
	}

	info, err := bot.GetWebhookInfo()
	if err != nil {
		log.Fatal(err)
	}

	if info.LastErrorDate != 0 {
		log.Printf("Telegram callback failed: %s", info.LastErrorMessage)
	}

	updates := bot.ListenForWebhook("/" + bot.Token)
	go http.ListenAndServeTLS("0.0.0.0:8443", "fullchain.pem", "privkey.pem", nil)

	for update := range updates {
		log.Printf("%+v\n", update)
	}
}
```
works fine.
and answer on getWebhookInfo

```json
{
	"ok": true,
	"result": {
	  "url": "https://domain.com:8443/123456789:AbCdEfGhIjKlMnOpQrStUvWxYz012345678",
	  "has_custom_certificate": false,
	  "pending_update_count": 0,
	  "last_error_date": 1656883643,
	  "last_error_message": "Connection refused",
	  "max_connections": 40,
	  "ip_address": "1.2.3.4"
	}
  }
```
 I guess the certificate parameter in https://core.telegram.org/bots/api#setwebhook needed only for a self-signed certificates

**Comment by SakoDroid** [comment] 2022-07-04 22:38
Hi, first of all sorry for answering a little late.
Thank you for notiftying us about such error. This error is caused by a bug in the code and it will be fixed in the next release.

**Closed by SakoDroid** 2022-07-04 22:38 UTC
